### ISSUE TITLE
Allow unlimited site coordinators per site

### ISSUE THREAD

**Issue by Klaital** [Klaital/vitasa-web#10]
As a site coordinator, I want to be able to help manage any site, even if it already has another site coordinator.

**Comment by Klaital** [comment]
@coxthepilot How do you want the API structured for this?

## Option 1:

I create two new APIs for adding and removing users as sitecoordinator for a site:

    # Add a user as a SC for this site
    POST /sites/{slug}/coordinators/{user_id}
    # Remove this user from coordinating this site
    DELETE /sites/{slug}/coordinators/{user_id}

I could also include

    GET /sites/{slug}/coordinators/

to fetch a list of the coordinators for a site.

## Option 2:

I allow an array of user IDs to be sent as part of the Site Update API, which will entirely overwrite the set of SC's currently assigned to a site.

**Comment by coxthepilot** [comment]
I vote for option 2; I just keep a list and send it to you on an update. Can that work?
