### ISSUE TITLE
Notifications and SMS not being received

### ISSUE THREAD

**Issue by coxthepilot** [Klaital/vitasa-web#121]
As Admin or SuperAdmin, sending notifications to Volunteers are not received. Same is true for volunteers with opt-in and a valid phone number.

**Comment by Klaital** [comment]
Not tested much other than for regressions, but I have new code up on staging. Let me know how it looks before I push to production. It might fix #124 as well, but I haven't tested that at all.

**Comment by coxthepilot** [comment]
I'm closing this one since notifications seem to be working. SMS is still not working...
