### ISSUE TITLE
phone updates doesn't stick

### ISSUE THREAD

**Issue by coxthepilot** [Klaital/vitasa-web#23]
Logged in as SiteCoordinator tried to change his phone number; the change didn't stick. Tried changing when logged in as Admin with the same result

**Comment by coxthepilot** [comment]
Have verified that "phone" is being supplied in the input, the value returned has "phone" as "null"

**Comment by Klaital** [comment]
There was a bug in the way input parameters were filtered out based on user role. It was fixed as a part of #26, and I think it was the root cause of this bug as well.

Regardless, I'm not seeing this behavior now.
