### ISSUE TITLE
Volunteer mobile subscription

### ISSUE THREAD

**Issue by coxthepilot** [Klaital/vitasa-web#27]
As a Volunteer on the Mobile team (role includes Mobile), I would like to opt-in to receive notifications when a change occurs to a Mobile site (site capabilities includes Mobile) such as any change to the calendar, location, etc. This is an opt-in meaning that not all Volunteers on the Mobile team will get notifications, just the ones that opt-in.

**Comment by Klaital** [comment]
We have added a field on users called `subscribe_mobile`. It will be used to control whether a user gets notifications about mobile sites.
