### ISSUE TITLE
Calendar entry time values are full date + time

### ISSUE THREAD

**Issue by coxthepilot** [Klaital/vitasa-web#31]
A calendar entry has entries for open time and close time; they appear to be stored in some kind of datetime format; suggest just treat as a string.

I submit "10:00" for storage. On return I get "2000-01-01 10:00:00 UTC"

**Comment by Klaital** [comment]
I'm storing them as a TimeOfDay (https://github.com/jackc/tod), but they're supposed to serialize to a simple string like "10:00". I must have broken the serializer when stripping out shifts.

**Comment by Klaital** [comment]
Fixed in 465b190de6b216e4b777c538e638a2d1ea0c930a
