### ISSUE TITLE
Bad format of object in sitecoordinators caused error 500

### ISSUE THREAD

**Issue by coxthepilot** [Klaital/vitasa-web#40]
In a PUT on /sites/{slug} the json body had an improperly formatted sitecoordinators field (an array of ints rather than array of { "id": 4 }. The result was an error 500

**Comment by Klaital** [comment]
Is this still an issue? Looking at the code, the Site Update operation should yield a standard Show Site view, which should be rendering the site coordinators' data as an array of `{"id" 1, "name":"Chris"}`
