### ISSUE TITLE
Updating the sites a user coordinates

### ISSUE THREAD

**Issue by coxthepilot** [Klaital/vitasa-web#42]
Doing a PUT on a user to update the sites coordinated by that user. Log (below) would imply that the sites_coordinated is not an allowed field to update. This seems to work from the app however and not clear why.

The end result is that the sites_coordinated is silently ignored by the PUT.

D, [2018-12-05T03:16:17.795824 #15010] DEBUG -- : [80d6d0ec-7ed2-4573-8773-74c4fd996310] User logged in? true
D, [2018-12-05T03:16:17.795862 #15010] DEBUG -- : [80d6d0ec-7ed2-4573-8773-74c4fd996310] 
D, [2018-12-05T03:16:17.795896 #15010] DEBUG -- : [80d6d0ec-7ed2-4573-8773-74c4fd996310] Users: current=179, accessing=65
D, [2018-12-05T03:16:17.795927 #15010] DEBUG -- : [80d6d0ec-7ed2-4573-8773-74c4fd996310] Accessing self? false
D, [2018-12-05T03:16:17.795963 #15010] DEBUG -- : [80d6d0ec-7ed2-4573-8773-74c4fd996310] Admin? true
D, [2018-12-05T03:16:17.795996 #15010] DEBUG -- : [80d6d0ec-7ed2-4573-8773-74c4fd996310] Permitting admin-only user fields
D, [2018-12-05T03:16:17.796029 #15010] DEBUG -- : [80d6d0ec-7ed2-4573-8773-74c4fd996310] Adding Admin fields
D, [2018-12-05T03:16:17.796068 #15010] DEBUG -- : [80d6d0ec-7ed2-4573-8773-74c4fd996310] Permitting these fields: [:roles, :role_ids, :certification, :name, :password, :password_confirmation, :phone, :email]
D, [2018-12-05T03:16:17.796367 #15010] DEBUG -- : [80d6d0ec-7ed2-4573-8773-74c4fd996310] Filtered params: {"certification"=>"None", "name"=>"sc tester", "password"=>nil, "phone"=>"123-123-1237", "email"=>"sctester@a.c"}
D, [2018-12-05T03:16:17.796653 #15010] DEBUG -- : [80d6d0ec-7ed2-4573-8773-74c4fd996310] Permitted params: <ActionController::Parameters {"certification"=>"None", "name"=>"sc tester", "password"=>nil, "phone"=>"123-123-1237", "email"=>"sctester@a.c"} permitted: true>
D, [2018-12-05T03:16:17.796707 #15010] DEBUG -- : [80d6d0ec-7ed2-4573-8773-74c4fd996310] Removing password fields: {"certification"=>"None", "name"=>"sc tester", "password"=>nil, "phone"=>"123-123-1237", "email"=>"sctester@a.c"}
D, [2018-12-05T03:16:17.796900 #15010] DEBUG -- : [80d6d0ec-7ed2-4573-8773-74c4fd996310]    (0.1ms)  BEGIN
D, [2018-12-05T03:16:17.798262 #15010] DEBUG -- : [80d6d0ec-7ed2-4573-8773-74c4fd996310]   User Exists (0.3ms)  SELECT  1 AS one FROM `users` WHERE `users`.`email` = 'sctester@a.c' AND (`users`.`id` != 65) LIMIT 1
D, [2018-12-05T03:16:17.799069 #15010] DEBUG -- : [80d6d0ec-7ed2-4573-8773-74c4fd996310]    (0.1ms)  COMMIT
D, [2018-12-05T03:16:17.800828 #15010] DEBUG -- : [80d6d0ec-7ed2-4573-8773-74c4fd996310]   WorkLog Load (0.2ms)  SELECT `work_logs`.* FROM `work_logs` WHERE `work_logs`.`user_id` = 65
D, [2018-12-05T03:16:17.802119 #15010] DEBUG -- : [80d6d0ec-7ed2-4573-8773-74c4fd996310]   Site Load (0.3ms)  SELECT `sites`.* FROM `sites` INNER JOIN `users_sites` ON `sites`.`id` = `users_sites`.`site_id` WHERE `users_sites`.`user_id` = 65
D, [2018-12-05T03:16:17.804159 #15010] DEBUG -- : [80d6d0ec-7ed2-4573-8773-74c4fd996310]   Suggestion Load (0.2ms)  SELECT `suggestions`.* FROM `suggestions` WHERE `suggestions`.`user_id` = 65
I, [2018-12-05T03:16:17.806244 #15010]  INFO -- : [80d6d0ec-7ed2-4573-8773-74c4fd996310] {"method":"PUT","path":"/users/65","format":"json","controller":"UsersController","action":"update","status":200,"duration":15.18,"view":5.67,"db":2.58,"time":"2018-12-05T03:16:17.790+00:00","params":{"id":"65","name":"sc tester","password":"[FILTERED]","password_confirm":"[FILTERED]","email":"sctester@a.c","phone":"123-123-1237","certification":"None","roles":["SiteCoordinator"],"sites_coordinated":[{"id":65,"slug":"adult-education-center"},{"id":30,"slug":"citi-bank"},{"id":10,"slug":"henry-guerra-library"},{"id":9,"slug":"only-open-once"}],"controller":"users","action":"update","user":{"password":"[FILTERED]","roles":["SiteCoordinator"],"email":"sctester@a.c","phone":"123-123-1237","certification":"None","name":"sc tester"}},"cookie":"_rails-base_session=cXkzUURxUTlsaXBVaWgybkN5M0NJN2hsVmFDbXhGVVlFTzRpdnFEdUcvR1J6SU5pcURUV0F4enpCM0FyQ1lQYzB2QlJBVTRUcGpWVC8wUERzc0tpNVB3aEgwMlJ3clgyNmZSMFFaaXlNa1hnRjM2T0U3dHJaSW9Yc0hFVnJiZ2luRlRyTzRiYlVPRjIzSDhhZ3V1cXRJMkxtQXo5dmh3Y3lRLzFCd2dGTFNzPS0ta1E5dHF1RENJQm9VTDExTDUwTUJ6dz09--f31a45ee91eccb038501c525fadd4e94328784a0","@timestamp":"2018-12-05T03:16:17.805Z","@version":"1","message":"[200] PUT /users/65 (UsersController#update)"}

**Comment by Klaital** [comment]
Should be fixed.
