### ISSUE TITLE
Error 500 in site create

### ISSUE THREAD

**Issue by coxthepilot** [Klaital/vitasa-web#45]
POST on SITES got an error 500. Log details are below

`D, [2018-12-06T03:01:13.483118 #21453] DEBUG -- : [4aa6ffd6-1a0f-4c42-a0ff-1a51e4ab245c]   User Load (0.3ms)  SELECT  `users`.* FROM `users` WHERE `users`.`id` = 179 LIMIT 1
D, [2018-12-06T03:01:13.484689 #21453] DEBUG -- : [4aa6ffd6-1a0f-4c42-a0ff-1a51e4ab245c]   Role Load (0.3ms)  SELECT `roles`.* FROM `roles` INNER JOIN `role_grants` ON `roles`.`id` = `role_grants`.`role_id` WHERE `role_grants`.`user_id` = 179
D, [2018-12-06T03:01:13.485168 #21453] DEBUG -- : [4aa6ffd6-1a0f-4c42-a0ff-1a51e4ab245c]    (0.1ms)  BEGIN
D, [2018-12-06T03:01:13.486075 #21453] DEBUG -- : [4aa6ffd6-1a0f-4c42-a0ff-1a51e4ab245c]   Site Exists (0.2ms)  SELECT  1 AS one FROM `sites` WHERE `sites`.`slug` = BINARY 'sac-student-advocacy-bldg' LIMIT 1
D, [2018-12-06T03:01:13.487549 #21453] DEBUG -- : [4aa6ffd6-1a0f-4c42-a0ff-1a51e4ab245c]   SQL (0.2ms)  INSERT INTO `sites` (`name`, `street`, `city`, `state`, `zip`, `latitude`, `longitude`, `created_at`, `updated_at`, `google_place_id`, `slug`, `contact_name`, `contact_phone`, `notes`) VALUES ('SAC Student Advocacy Bldg', '1819 N Main', 'San Antonio', 'TX', '78212', '29.4461783388585', '-98.4943822331406', '2018-12-06 03:01:13', '2018-12-06 03:01:13', '', 'sac-student-advocacy-bldg', '', '', '')
D, [2018-12-06T03:01:13.489129 #21453] DEBUG -- : [4aa6ffd6-1a0f-4c42-a0ff-1a51e4ab245c]    (1.2ms)  COMMIT
I, [2018-12-06T03:01:13.490388 #21453]  INFO -- : [4aa6ffd6-1a0f-4c42-a0ff-1a51e4ab245c] {"method":"POST","path":"/sites","format":"json","controller":"SitesController","action":"create","status":500,"error":"ActionController::UrlGenerationError: No route matches {:action=\u003e\"schedule\", :controller=\u003e\"aggregates\"}","duration":9.32,"view":0.0,"db":2.4,"time":"2018-12-06T03:01:13.480+00:00","params":{"name":"SAC Student Advocacy Bldg","slug":"","street":"1819 N Main","city":"San Antonio","state":"TX","zip":"78212","latitude":"29.4461783388585","longitude":"-98.4943822331406","google_place_id":"","contact_name":"","contact_phone":"","notes":"","calendar_overrides":[],"site_features":["Fixed"],"sitecoordinators":[],"controller":"sites","action":"create","site":{"name":"SAC Student Advocacy Bldg","street":"1819 N Main","city":"San Antonio","state":"TX","zip":"78212","latitude":"29.4461783388585","longitude":"-98.4943822331406","google_place_id":"","slug":"","contact_name":"","contact_phone":"","notes":""}},"cookie":"_rails-base_session=Z201U3FGUndUUU9nQ1g2S004bzRSMHgrRGYydlhDck1GQ1lwSkpDVVdSM0lBUmtPR09XdUZSeGVFZ0tFSDdybldJeWwxR1JCWGcycjVkeElNZVM5a3c9PS0tSFBnaUk1a3lzSEg1TFRDdG5kUytJQT09--197d86484bddc2a18aa12270152537f1c44f5389","@timestamp":"2018-12-06T03:01:13.489Z","@version":"1","message":"[500] POST /sites (SitesController#create)"}
F, [2018-12-06T03:01:13.490929 #21453] FATAL -- : [4aa6ffd6-1a0f-4c42-a0ff-1a51e4ab245c]   
F, [2018-12-06T03:01:13.490980 #21453] FATAL -- : [4aa6ffd6-1a0f-4c42-a0ff-1a51e4ab245c] ActionController::UrlGenerationError (No route matches {:action=>"schedule", :controller=>"aggregates"}):
F, [2018-12-06T03:01:13.491018 #21453] FATAL -- : [4aa6ffd6-1a0f-4c42-a0ff-1a51e4ab245c]   
F, [2018-12-06T03:01:13.491054 #21453] FATAL -- : [4aa6ffd6-1a0f-4c42-a0ff-1a51e4ab245c] app/controllers/sites_controller.rb:77:in `block in create'
[4aa6ffd6-1a0f-4c42-a0ff-1a51e4ab245c] app/controllers/sites_controller.rb:72:in 'create'`

**Comment by Klaital** [comment]
Should be fixed.

**Comment by coxthepilot** [comment]
Still happening this afternoon;

**Comment by coxthepilot** [comment]
is fixed
