### ISSUE TITLE
error 500 on user subscribing to mobile updates

### ISSUE THREAD

**Issue by coxthepilot** [Klaital/vitasa-web#50]
Unsubscribe works fine. Just the act of subscribing fails.

PUT on /users/215 with `{"id" : "215","name" : "vol tester mobile 4th a","email" : "voltestermobile@a.c","phone" : "123-123-1234","certification" : "None","subscribe_mobile" : true,"roles" : ["Volunteer","Mobile"],"preferred_sites" : ["guadalupe-community-center","san-antonio-college-student-advocacy-bldg"]}`

server log:
 `I, [2018-12-12T16:45:17.370060 #4110]  INFO -- : [53bb3704-9231-4825-aaec-343d73236816] {"method":"PUT","path":"/users/215","format":"json","controller":"UsersController","action":"update","status":500,"error":"NoMethodError: undefined method `platform' for #\u003cUser:0x007f26e1226f28\u003e","duration":27.54,"view":0.0,"db":2.18,"time":"2018-12-12T16:45:17.341+00:00","params":{"id":"215","name":"vol tester mobile 4th a","email":"voltestermobile@a.c","phone":"123-123-1234","certification":"None","subscribe_mobile":true,"roles":["Volunteer","Mobile"],"preferred_sites":["guadalupe-community-center","san-antonio-college-student-advocacy-bldg"],"controller":"users","action":"update","user":{"roles":["Volunteer","Mobile"],"email":"voltestermobile@a.c","phone":"123-123-1234","certification":"None","name":"vol tester mobile 4th a","subscribe_mobile":true}},"cookie":"_rails-base_session=SjRiYmRUVFVSUVZuN2xYUkRUcmN4YjlpUFdWQTBqTmJVWDB0QSt4S1ZUa3NLUk9EVkJoT3VLeGM3c2FNU0NXd0xKUDFBVk1GN2dyUUF0N3dtc2loV3c9PS0tQjZPN25CZDJNRjk0cDZySmk4K2JtZz09--47bf8f51a669c64ef4e9020405b76d9f8600c55a","@timestamp":"2018-12-12T16:45:17.369Z","@version":"1","message":"[500] PUT /users/215 (UsersController#update)"}
F, [2018-12-12T16:45:17.371199 #4110] FATAL -- : [53bb3704-9231-4825-aaec-343d73236816]   
F, [2018-12-12T16:45:17.371426 #4110] FATAL -- : [53bb3704-9231-4825-aaec-343d73236816] NoMethodError (undefined method `platform' for #<User:0x007f26e1226f28>):
F, [2018-12-12T16:45:17.371479 #4110] FATAL -- : [53bb3704-9231-4825-aaec-343d73236816]   
F, [2018-12-12T16:45:17.371528 #4110] FATAL -- : [53bb3704-9231-4825-aaec-343d73236816] app/models/user.rb:121:in `register_mobile_updates'
[53bb3704-9231-4825-aaec-343d73236816] app/controllers/users_controller.rb:112:in `block in update'
[53bb3704-9231-4825-aaec-343d73236816] app/controllers/users_controller.rb:111:in `update'
`

**Comment by Klaital** [comment]
Fixed in facb4b1f1e3bf9b794e7ecbc487828d6ccf87385
