### ISSUE TITLE
New role: Monitor

### ISSUE THREAD

**Issue by coxthepilot** [Klaital/vitasa-web#55]
We need a role of 'Monitor' to allow folks who are not tax preparers, site coordinators, or admins. A Monitor can see users and sites, can receive notifications of changes to sites, but cannot make changes.

**Comment by coxthepilot** [comment]
Monitor must opt-in for notifications or texts

**Comment by Klaital** [comment]
What can a Monitor do that a default Volunteer cannot?

**Comment by coxthepilot** [comment]
A monitor is more like a read-only admin; get sites, users, view notifications, view suggestions; but cannot change or edit any of the above

**Comment by Klaital** [comment]
Role created in staging.
