### ISSUE TITLE
Users need to have additional flags

### ISSUE THREAD

**Issue by coxthepilot** [Klaital/vitasa-web#60]
With increased use by the organization, we need each user to carry the following boolean flags
- OVASE (this is their name for safe environment training)
- Agreement signed
- Background check completed

**Comment by Klaital** [comment]
This is now managed by a set of new APIs.

Organization Admins can create Certifications using `POST /certifications`, with the body specifying the name: `{"name": "HSA"}`
Use `GET /certifications` to see the list of available certs for your organization with their names and cert IDs.

To grant a certification to a specific user, call `PUT /users/:user_id/certifications/:cert_id` (no request body needed)
To revoke a certification from a specific user, call `DELETE /users/:user_id/certifications/:cert_id`
