### ISSUE TITLE
Notifications (app or SMS) can be directed to a specific role

### ISSUE THREAD

**Issue by coxthepilot** [Klaital/vitasa-web#62]
Notifications, whether an app message or a text message if the user opted-in, can be directed uniquely based on role: Intake, Volunteer, Site Coordinator, Admin, SuperAdmin

Ideally a given notification can be sent to a combination of roles

**Comment by Klaital** [comment]
I'm implementing a new value for the "audience" field on a NotificationRequest. Before, the supported values were "volunteers" and "sc". Now supported is "role-$rolename", to direct a notification to all users with the specified role. For example, use "role-Admin" or "role-SuperAdmin" (though the value is not case sensitive).
