### ISSUE TITLE
Slow to load all sites and all users

### ISSUE THREAD

**Issue by coxthepilot** [Klaital/vitasa-web#63]
Wait times for sites (5 sec) and users (7 sec) is too long. Note that this is the wait time as viewed from the http connection. The transfer times were all under 100ms.

**Comment by Klaital** [comment]
I think I've got fragment caching figured out. It nearly eliminated the complex database queries for loading the sites index. I'll see about getting users properly cached as well.

**Comment by coxthepilot** [comment]
With a full compliment of sites, the wait time is 183ms, transfer time is 484ms. Looks like the cacheing is working.
