### ISSUE TITLE
Multiple organization support

### ISSUE THREAD

**Issue by coxthepilot** [Klaital/vitasa-web#65]
I need to be able to have multiple organizations active in the system during a tax season. I need users and sites in each organization along with admins, volunteers, and site coordinators. The users in one organization should be able to see the elements in other organizations.

Notifications need to only go to users in that organization. Ex: new site would only go to admins in that site's organization; same with new users.

Suggestions would only be visible to the admins in that organization.

**Comment by Klaital** [comment]
Implementation is complete in master.

New APIs: 
* ListOrganizations: `GET /organizations`
* CreateOrganization: `POST /organizations`

**Comment by coxthepilot** [comment]
Is working as planned.
