### ISSUE TITLE
New User Registration gets error 500

### ISSUE THREAD

**Issue by coxthepilot** [Klaital/vitasa-web#67]
As part of the user signup process, we need users to go through a user registration process using the Register User api. When I make the call I get an error 500. Did we disable the call in previous versions? If so, I need it re-enabled and extended to include the Organization

**Comment by Klaital** [comment]
I'm not going to be bugfixing on the production site, given the major overhaul that we have underway. New user registration is definitely working in the master branch as of 6e05ac4232bd5728c2d89062eb75ff6d1f614ea5: see #61
