### ISSUE TITLE
WorkLog not added to user

### ISSUE THREAD

**Issue by coxthepilot** [Klaital/vitasa-web#68]
Applies to staging.volunteer-savvy.com

When creating a worklog for a user (POST /users/id/work_logs), the call is successful but the returned user does not have the new worklog in response.

json body is:
`approved: "false"
date: "2019-09-25"
hours: "1"
id: "-1"
site: "guadalupe-community-center"'

**Comment by Klaital** [comment]
Hm, this sounds a lot like the caching error we discussed last night. This will take a little digging.

**Comment by Klaital** [comment]
I think I found the magic for this using Rails' model dependency functions. See https://github.com/Klaital/vitasa-web/commit/f0b15c0285bf4b4862820486d92f082ea5c6855e

**Comment by coxthepilot** [comment]
Seems to be working
