### ISSUE TITLE
Role of Monitor not saved

### ISSUE THREAD

**Issue by coxthepilot** [Klaital/vitasa-web#72]
As a SuperAdmin, PUT users/id with roles containing Monitor returns as roles Volunteer with no error. Setting the user role of Monitor does not stick.

**Comment by coxthepilot** [comment]
It looks like any change to the user Role doesn't stick; As SuperAdmin, I created a user and then tried to make that user an Admin but reverted back to Volunteer. Same with Site Coordinator.

**Comment by Klaital** [comment]
How are you setting the user role? Can you include the JSON you're submitting? 

It seems to work fine in testing, so I'm obviously not doing the same thing exactly.

**Comment by coxthepilot** [comment]
Just did a retest; seems to be working

here is the json going in
`{
    "id":9,
    "name":"monitor",
    "email":"m@gmail.com",
    "phone":"123-123-1234",
    "certification":"None",
    "roles":["Monitor","Mobile"],
    "preferred_sites":[],
    "subscribe_mobile":false,
    "sites_coordinated":[],
    "hsa_certification":false,
    "military_certification":false,
    "organization_id":1
}`
