### ISSUE TITLE
Updates to user don't stick (HSA, Military)

### ISSUE THREAD

**Issue by coxthepilot** [Klaital/vitasa-web#81]
As SuperAdmin and Admin, updating HSA or Military doesn't stick. I suspect there is a new model and I'm not up to date

**Comment by Klaital** [comment]
User certifications are managed using a new set of APIs for Certifications

List all certification for your organization: 

    GET /certifications


An admin can create or delete Certifications using

    POST /certifications
    { "name": "new certification"}
   
    DELETE /certifications/:id

Then the Certs can be applied to a user with

    PUT /users/:user_id/certifications/:cert_id

and revoked with 

    DELETE /users/:user_id/certifications/:cert_id

**Comment by coxthepilot** [comment]
Upgraded to new structure; bug no longer applies
