### ISSUE TITLE
Error 500 on create calendar entry for site

### ISSUE THREAD

**Issue by coxthepilot** [Klaital/vitasa-web#82]
As Admin, doing a POST on sites/{slug}/calendars/ with 
"{"siteid":134,"date":"2020-01-01","is_closed":true,"open":"08:00:00","close":"17:00:00"}"
returns error 500 (internal error)

**Comment by Klaital** [comment]
Not seeing this error in test after setting mocks on the SNS client. I'll need to check the staging server logs for more information, but it's probably an issue around sending notifications on updated sites.

**Comment by coxthepilot** [comment]
Believe this is related to the error 500 on sites with Mobile. Closing as duplicate.
