### ISSUE TITLE
Update to Organization gets 401

### ISSUE THREAD

**Issue by coxthepilot** [Klaital/vitasa-web#83]
As SuperAdmin I do a PUT to /organizations/{id} with
"{"organization_id":"8","name":"Cameron County 1","slug":"cameron-county"}"
and get a 401 in response

**Comment by Klaital** [comment]
That was a stupid bug. Only Org Admins could do an update, not SuperAdmins.

Fixed in 71f03db, but not yet deployed to staging.

**Comment by coxthepilot** [comment]
Works as expected.
