### ISSUE TITLE
Update to logged in user gets 401

### ISSUE THREAD

**Issue by coxthepilot** [Klaital/vitasa-web#85]
As a Volunteer, I update my settings (PUT, /user/id/) and get a 401 (unauthorized).

**Comment by coxthepilot** [comment]
Additional info: seems to work ok if logged user is Admin (an Admin can update their settings) but a Volunteer cannot. Should allow a user to update their own record

**Comment by coxthepilot** [comment]
Site Coordinator cannot save their settings either

**Comment by Klaital** [comment]
The http response body should have information about why the request was refused. There are a few code paths on Update User that can generate a 401 response - not logged in, or not logged in to a user able to edit the requested fields on the specified user.

Most likely, this looks like a user trying to update their list of Roles - only Admins can do that.

If it simplifies the client code to just submit the whole user object every time, I can change the server to simply silently ignore the `roles` field unless the requesting user is an Admin.

**Comment by coxthepilot** [comment]
Changed the tojson function to not include roles except for admin user updates
