### ISSUE TITLE
Update to user certifications sticks, eventually

### ISSUE THREAD

**Issue by coxthepilot** [Klaital/vitasa-web#89]
As an Admin, I add a cert (HSA) to a user and verify that it is there by reloading the user (GET /users/13).

Then remove the cert (HSA), reload the user, and the cert is still there. If I then update something else in the user, the phone number of example, and the reload the user, the phone is changed and the cert shows as removed.

Perhaps a change to certs isn't triggering a cache update?

**Comment by coxthepilot** [comment]
Definitely looking like changes to certs do not cause the user cache to be updated

**Comment by Klaital** [comment]
Probably the same problem as in #94, and I've implemented the same workaround.
