### ISSUE TITLE
SuperAdmin needs to be able to maintain the certifications

### ISSUE THREAD

**Issue by coxthepilot** [Klaital/vitasa-web#90]
As a SuperAdmin, making the calls to create an org level certification gets a 401. Works ok for an admin. Need the ability for the SuperAdmin to maintain the list.

**Comment by Klaital** [comment]
The expectation had been that the certification would be forcibly assigned to the creating user's Organization, and SuperAdmins couldn't be assumed to be part of an Org.

The new logic is that the `organization_id` field will be permitted in the POST payload, but anyone other than a SuperAdmin will have this value ignored in favor of their own organization ID.
