### ISSUE TITLE
404 on Update or Delete of workitem

### ISSUE THREAD

**Issue by coxthepilot** [Klaital/vitasa-web#94]
As SiteCoordinator, trying to update some (most) WorkItems gets a 404; also happens on delete

Is there a cacheing issue where they appear to exist really don't?

**Comment by Klaital** [comment]
Yep, it's a caching problem. Rails isn't executing the registered callbacks on WorkLog objects for some reason. I've added a workaround, but I'm not sure what the root cause is.
