### ISSUE TITLE
Need flag for opt-in to text messages

### ISSUE THREAD

**Issue by coxthepilot** [Klaital/vitasa-web#98]
A a Volunteer, I want to be able to opt-in for text messages in lieu of notifications. If I have the app installed and I've logged in, send me a notification through the app. If I do not have the app installed and I have opted-in for text messages, send me the notification to the phone number I've entered on my profile.

Need the field added to the user.

Note that I don't need support for SMS messaging at this point, just the field added to the user structure. Support for messaging can come later.

**Comment by Klaital** [comment]
Added flag `sms_optin`. There is no server-side check (yet) requiring there to actually be a phone number set when enabling this flag, but I probably will add something like that when I actually implemnt the SMS fallback code.
